-- Create module table
CREATE TABLE module (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    version BIGINT
);

-- Create feature table
CREATE TABLE feature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    module_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    version BIGINT,
    CONSTRAINT fk_feature_module FOREIGN KEY (module_id) REFERENCES module(id)
);

-- Create tenant_module table
CREATE TABLE tenant_module (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    module_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    enabled_at TIMESTAMP,
    disabled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    version BIGINT,
    CONSTRAINT fk_tenant_module_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id),
    CONSTRAINT fk_tenant_module_module FOREIGN KEY (module_id) REFERENCES module(id),
    CONSTRAINT uk_tenant_module UNIQUE (tenant_id, module_id)
);

-- Insert initial modules
INSERT INTO module (name, code, description, active, created_at, created_by)
VALUES 
('Dairy Management', 'DAIRY', 'Module for managing dairy operations', true, NOW(), 'system'),
('Pottery Management', 'POTTERY', 'Module for managing pottery operations', true, NOW(), 'system'),
('Garments Management', 'GARMENTS', 'Module for managing garments operations', true, NOW(), 'system');

-- Insert initial features for Dairy module
INSERT INTO feature (name, code, description, active, module_id, created_at, created_by)
SELECT 
    'Milk Collection', 'DAIRY_MILK_COLLECTION', 'Feature for managing milk collection', true, id, NOW(), 'system'
FROM module WHERE code = 'DAIRY';

INSERT INTO feature (name, code, description, active, module_id, created_at, created_by)
SELECT 
    'Production', 'DAIRY_PRODUCTION', 'Feature for managing dairy production', true, id, NOW(), 'system'
FROM module WHERE code = 'DAIRY';

INSERT INTO feature (name, code, description, active, module_id, created_at, created_by)
SELECT 
    'Inventory', 'DAIRY_INVENTORY', 'Feature for managing dairy inventory', true, id, NOW(), 'system'
FROM module WHERE code = 'DAIRY'; 