-- Create dairy module entities with Company associations
-- V40__create_dairy_entities.sql

-- ============================================
-- Milk Collection Branch Table
-- ============================================
CREATE TABLE milk_collection_branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Basic Information
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) NOT NULL,
    address TEXT,
    phone VARCHAR(20),
    contact_number VARCHAR(20),
    
    -- Capacity Information
    capacity_liters INTEGER,
    current_stock_liters INTEGER DEFAULT 0,
    chill_vat_count INTEGER DEFAULT 0,
    
    -- Status
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    
    -- ============ COMPANY ASSOCIATION (COMPOSITION) ============
    -- This is the key requirement - explicit Company association
    company_id BIGINT NOT NULL,
    
    -- Other Relationships
    tenant_id BIGINT NOT NULL,
    manager_id BIGINT,
    
    -- BaseEntity Audit Fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    
    -- Foreign Key Constraints
    CONSTRAINT fk_mcb_company FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE,
    CONSTRAINT fk_mcb_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE,
    CONSTRAINT fk_mcb_manager FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL,
    
    -- Unique Constraints
    CONSTRAINT uk_mcb_code_company UNIQUE (code, company_id)
);

-- ============================================
-- Factory Table
-- ============================================
CREATE TABLE factory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Basic Information
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) NOT NULL,
    address TEXT,
    phone VARCHAR(20),
    contact_number VARCHAR(20),
    
    -- Production Information
    production_capacity_per_day INTEGER,
    current_production INTEGER DEFAULT 0,
    factory_type VARCHAR(50), -- PROCESSING, PACKAGING, STORAGE, MIXED
    certifications TEXT, -- JSON or comma-separated
    
    -- Status
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    
    -- ============ COMPANY ASSOCIATION (COMPOSITION) ============
    -- This is the key requirement - explicit Company association
    company_id BIGINT NOT NULL,
    
    -- Other Relationships
    tenant_id BIGINT NOT NULL,
    manager_id BIGINT,
    
    -- BaseEntity Audit Fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    
    -- Foreign Key Constraints
    CONSTRAINT fk_factory_company FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE,
    CONSTRAINT fk_factory_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE,
    CONSTRAINT fk_factory_manager FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL,
    
    -- Unique Constraints
    CONSTRAINT uk_factory_code_company UNIQUE (code, company_id)
);

-- ============================================
-- Shop Table
-- ============================================
CREATE TABLE shop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Basic Information
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) NOT NULL,
    address TEXT,
    phone VARCHAR(20),
    contact_number VARCHAR(20),
    
    -- Sales Information
    daily_sales DECIMAL(12,2),
    monthly_sales DECIMAL(12,2),
    shop_type VARCHAR(50), -- RETAIL, WHOLESALE, FRANCHISE, ONLINE, KIOSK
    
    -- Operational Information
    opening_hours VARCHAR(100),
    delivery_radius_km INTEGER,
    storage_capacity_liters INTEGER,
    
    -- Status
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    
    -- ============ COMPANY ASSOCIATION (COMPOSITION) ============
    -- This is the key requirement - explicit Company association
    company_id BIGINT NOT NULL,
    
    -- Other Relationships
    tenant_id BIGINT NOT NULL,
    manager_id BIGINT,
    
    -- BaseEntity Audit Fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    
    -- Foreign Key Constraints
    CONSTRAINT fk_shop_company FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE,
    CONSTRAINT fk_shop_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE,
    CONSTRAINT fk_shop_manager FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL,
    
    -- Unique Constraints
    CONSTRAINT uk_shop_code_company UNIQUE (code, company_id)
);

-- ============================================
-- Indexes for Performance
-- ============================================

-- MCB Indexes
CREATE INDEX idx_mcb_company_id ON milk_collection_branch(company_id);
CREATE INDEX idx_mcb_tenant_id ON milk_collection_branch(tenant_id);
CREATE INDEX idx_mcb_manager_id ON milk_collection_branch(manager_id);
CREATE INDEX idx_mcb_active ON milk_collection_branch(is_active);
CREATE INDEX idx_mcb_company_active ON milk_collection_branch(company_id, is_active);

-- Factory Indexes
CREATE INDEX idx_factory_company_id ON factory(company_id);
CREATE INDEX idx_factory_tenant_id ON factory(tenant_id);
CREATE INDEX idx_factory_manager_id ON factory(manager_id);
CREATE INDEX idx_factory_active ON factory(is_active);
CREATE INDEX idx_factory_company_active ON factory(company_id, is_active);
CREATE INDEX idx_factory_type ON factory(factory_type);

-- Shop Indexes
CREATE INDEX idx_shop_company_id ON shop(company_id);
CREATE INDEX idx_shop_tenant_id ON shop(tenant_id);
CREATE INDEX idx_shop_manager_id ON shop(manager_id);
CREATE INDEX idx_shop_active ON shop(is_active);
CREATE INDEX idx_shop_company_active ON shop(company_id, is_active);
CREATE INDEX idx_shop_type ON shop(shop_type);

-- ============================================
-- Comments for Documentation
-- ============================================

COMMENT ON TABLE milk_collection_branch IS 'Company-scoped milk collection branches for dairy operations';
COMMENT ON COLUMN milk_collection_branch.company_id IS 'Required association with Company - enforces company-level data isolation';
COMMENT ON CONSTRAINT uk_mcb_code_company IS 'Ensures unique MCB codes within each company scope';

COMMENT ON TABLE factory IS 'Company-scoped factories for dairy processing operations';
COMMENT ON COLUMN factory.company_id IS 'Required association with Company - enforces company-level data isolation';
COMMENT ON CONSTRAINT uk_factory_code_company IS 'Ensures unique factory codes within each company scope';

COMMENT ON TABLE shop IS 'Company-scoped shops for dairy retail/wholesale operations';
COMMENT ON COLUMN shop.company_id IS 'Required association with Company - enforces company-level data isolation';
COMMENT ON CONSTRAINT uk_shop_code_company IS 'Ensures unique shop codes within each company scope'; 