spring:
  application:
    name: dairymanagementsystem
  datasource:
    url: jdbc:postgresql://localhost:5432/dairy-management-system
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true 