spring:
  application:
    name: modulynx
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dairy_management_system
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Envers Configuration
        envers:
          audit_table_suffix: _aud
          revision_field_name: rev
          revision_type_field_name: revtype
          store_data_at_delete: true
          do_not_audit_optimistic_locking_field: true
          default_schema: public
          track_entities_changed_in_revision: true
          use_revision_entity_with_native_id: true
          global_with_modified_flag: true
          # Ensure we're using the custom revision entity table name
          revision_table_name: revinfo
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true
    validate-migration-naming: true
    validate-on-migrate: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
  show-actuator: true
  packages-to-scan: com.jaysambhu.modulynx

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:9c3e158958de16ec1534ca1e48c59c304e8eb291fd61ca8c492d05ed2b4cc8171d3defcb807abd9c1555cbba7ac6890b02324b8392c58acd655e0f9d8b9354bc}
  expiration: 86400000  # 24 hours in milliseconds

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Application Configuration
app:
  domain: localhost
  development-mode: true  # Enable development mode for local testing
  tenant:
    default: system
    reserved: www,admin,api,auth,mail,blog,docs,status
  admin:
    username: admin
    password: admin@123
    email: admin@modulynx.com

# Logging Configuration
logging:
  level:
    com.jaysambhu.modulynx: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: INFO 